# Generated by Django 2.2.6 on 2020-01-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('date_de_naissance', models.DateTimeField(verbose_name='date de naissance')),
                ('date_de_creation', models.DateField(auto_now=True)),
                ('date_de_maj', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
