# Generated by Django 2.2.6 on 2020-02-23 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospet',
            name='date_de_naissance',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de naissance'),
        ),
    ]
